


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ömer CENGİZ
 */
public class RenkUzayları extends javax.swing.JFrame {

    /**
     * Creates new form RenkUzayları
     */
    public RenkUzayları() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        butonRGB = new javax.swing.JButton();
        butonXYZ = new javax.swing.JButton();
        butonCIELab = new javax.swing.JButton();
        sec = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RENK UZAYLARI");
        setLocation(new java.awt.Point(450, 150));

        jLabel1.setText("HANGİ RENK UZAYI ILE RENK ANALAZI YAPACAKSINIZ");

        butonRGB.setBackground(new java.awt.Color(255, 255, 102));
        butonRGB.setText("RGB ");
        butonRGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonRGBActionPerformed(evt);
            }
        });

        butonXYZ.setBackground(new java.awt.Color(255, 255, 102));
        butonXYZ.setText("XYZ");
        butonXYZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonXYZActionPerformed(evt);
            }
        });

        butonCIELab.setBackground(new java.awt.Color(255, 255, 102));
        butonCIELab.setText("CIELab");
        butonCIELab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonCIELabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butonRGB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butonXYZ)
                        .addGap(44, 44, 44)
                        .addComponent(butonCIELab)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(40, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sec)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sec)
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonRGB)
                    .addComponent(butonXYZ)
                    .addComponent(butonCIELab))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void butonCIELabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonCIELabActionPerformed
      
        DosyaSecimi dosyaSecimi=new DosyaSecimi();
        dosyaSecimi.secım("CIELab");
        dosyaSecimi.setVisible(true);
        dispose();
              
    }//GEN-LAST:event_butonCIELabActionPerformed
    public String uzaySecım(){
        return sec.getText();
    }
    private void butonXYZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonXYZActionPerformed
        // TODO add your handling code here:

        DosyaSecimi dosyaSecimi=new DosyaSecimi();
        dosyaSecimi.secım("XYZ");
        dosyaSecimi.setVisible(true);
        dispose();
    }//GEN-LAST:event_butonXYZActionPerformed

    private void butonRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonRGBActionPerformed
        // TODO add your handling code here:
          DosyaSecimi dosyaSecimi=new DosyaSecimi();
        dosyaSecimi.secım("RGB");
        dosyaSecimi.setVisible(true);
        dispose();
    }//GEN-LAST:event_butonRGBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RenkUzayları.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RenkUzayları.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RenkUzayları.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RenkUzayları.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RenkUzayları().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonCIELab;
    private javax.swing.JButton butonRGB;
    private javax.swing.JButton butonXYZ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel sec;
    // End of variables declaration//GEN-END:variables
}
